### ISSUE TITLE
IOU on voxels for SN-Clean not exactly same as your claim in paper

### ISSUE THREAD

**Issue by shilei-ustcer** [davidstutz/aml-improved-shape-completion#1]
Hi, David,

Nice work!

When I evaluate the prtrained AML model provided by you on SN-Clean dataset, I find the IOU on voxels is 66%, but in your paper it is nearly 79%. So can you explain what I'm doing wrong?

![2019-07-09 00-50-18屏幕截图](https://user-images.githubusercontent.com/28994877/60827918-d681f500-a1e3-11e9-91ce-c496edbf0ff7.png)

**Comment by davidstutz** [comment]
From the code, evaluation seems to be the same as in [`aml/2_b_test.ppy`](https://github.com/davidstutz/aml-improved-shape-completion/blob/master/aml/2_b_test.py), so I would expect the same results. Are you using the correct model, i.e. the one trained on SN-clean?

Or did you already find the problem?

**Comment by shilei-ustcer** [comment]
Yes, my stupid mistake. Now for SN-clean, IOU of voxels is exactly same as in your paper.
But for completeness and accuracy measurement, my test result is smaller than in your paper. Did you use the measurement between mesh from predicted sdf and mesh from target sdf in the same resolution, both achieved using marching cube?

**Comment by davidstutz** [comment]
Sorry for the late reply! No I think, I computed the metrics between the predicted sdf (marching cubes) and the original mesh (not the derived sdf).
